inherit_gem:
    rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.7
  UseCache: true
  SuggestExtensions: false
  CacheRootDirectory: tmp
  Exclude:
    - 'test/fixtures/**/*'

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  IgnoredMethods:
  - require
  - require_relative
  - require_dependency
  - yield
  - raise
  Exclude:
  - Gemfile

Style/StringLiterals:
  EnforcedStyle: double_quotes

Sorbet/ConstantsFromStrings:
  Enabled: true

Sorbet/ForbidIncludeConstLiteral:
  Enabled: true

Sorbet/ParametersOrderingInSignature:
  Enabled: true

Sorbet/KeywordArgumentOrdering:
  Enabled: true

Sorbet/ValidSigil:
  Enabled: true

Performance/AncestorsInclude: # new in 1.7
  Enabled: false

Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: false

Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: false

Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: false

Performance/ConstantRegexp: # new in 1.9
  Enabled: false

Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: false

Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: false

Performance/RedundantSortBlock: # new in 1.7
  Enabled: false

Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: false

Performance/RedundantStringChars: # new in 1.7
  Enabled: false

Performance/ReverseFirst: # new in 1.7
  Enabled: false

Performance/SortReverse: # new in 1.7
  Enabled: false

Performance/Squeeze: # new in 1.7
  Enabled: false

Performance/StringInclude: # new in 1.7
  Enabled: false

Performance/Sum: # new in 1.8
  Enabled: false
