[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"
authors = ["Alex Evanczuk <alexevanczuk@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5.4" }
pks = { path = "../../../pks" }
serde = "~1"
serde_magnus = "~0.2"

