name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6
          - 2.7
    name: Tests Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Run style checks
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
  static-type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Run static type checks
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec srb tc
